//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingletonTestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int CustID { get; set; }
        public int CarID { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
